### ISSUE TITLE
this._reject is not a function

### ISSUE THREAD

**Issue by kurtextrem** [jeremyckahn/shifty#108] opened 2018-12-05 06:49 UTC
While trying out your solution: https://github.com/jeremyckahn/shifty/issues/107#issuecomment-444178869

I've encountered the following error:
Uncaught TypeError: this._reject is not a function shifty:2
    at t.value (shifty.js:2)

it happens when calling `.stop(false)` on an existing tweening instance (created with `new Tweenable`)

(same happens when I call `.stop(true)`, but with the error `this._resolve is not a function`)

**Comment by kurtextrem** [comment] 2018-12-05 06:54
So this happens when setConfig hasn't been called yet. Not sure if still an issue then. Feel free to close if you don't think it is.

**Comment by jeremyckahn** [comment] 2018-12-05 14:08
Hi @kurtextrem, I'd be curious to know what code is causing this error to occur. I can only see this happening if a new tween was started with no parameters and then`.stop()` was called. Assuming that's what's causing this, what is the use case for starting a tween without parameters?

**Comment by kurtextrem** [comment] 2018-12-05 17:16
No use case, it simply happened - so as I said feel free to close (in case you don't want to add a warning or so)

**Comment by jeremyckahn** [comment] 2018-12-05 17:45
Understood. It sounds like the API was not being used as intended, so I would prefer to make no change at this time. I am open to PRs to change the error handling, though!

I will close this for now. Thanks for reporting this issue, though!

**Closed by jeremyckahn** 2018-12-05 17:45 UTC
